# Generated by Django 5.0.6 on 2024-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_token', models.CharField(blank=True, max_length=255, null=True)),
                ('notion_database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
