# Generated by Django 5.0.6 on 2024-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='twitch_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='twitch_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
